### PR TITLE
Updated Meta.yaml Watchdog >=2.1.3

### PR DESCRIPTION
**Pull request by rxm7706**
Fixes https://github.com/conda-forge/jupyter_enterprise_gateway-feedstock/issues/34

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Review by kevin-bates — APPROVED** [review]
These changes look good.  I don't know conda-forge processes well enough to know what to do about the azure-related issues, however.

**Comment by rxm7706** [comment]
logs from azure failed build pasted below- not sure whats causing it but JEG troubleshooting says this could because of missing environment variables 

https://jupyter-enterprise-gateway.readthedocs.io/en/v1.0.0/troubleshooting.html

Drill down from the applicationId to find logs for the failed attempts and take appropriate actions. For example, for the error below,

Traceback (most recent call last):
 File "launch_ipykernel.py", line 7, in <module>
   from ipython_genutils.py3compat import str_to_bytes
 ImportError: No module named ipython_genutils.py3compat

Simply running “pip install ipython_genutils” should fix the problem. If Anaconda is installed, make sure the environment variable for Python, i.e. PYSPARK_PYTHON, is properly configured in the kernelspec and matches the actual Anaconda installation directory.


https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=491278&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=386

```
import: 'enterprise_gateway.services.sessions'
+ jupyter-enterprisegateway --help
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/jupyter_enterprise_gateway_1649803099392/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/jupyter-enterprisegateway", line 10, in <module>
    sys.exit(launch_instance())
  File "/home/conda/feedstock_root/build_artifacts/jupyter_enterprise_gateway_1649803099392/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/enterprise_gateway/__init__.py", line 7, in launch_instance
    from enterprise_gateway.enterprisegatewayapp import launch_instance
  File "/home/conda/feedstock_root/build_artifacts/jupyter_enterprise_gateway_1649803099392/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/enterprise_gateway/enterprisegatewayapp.py", line 37, in <module>
    from .services.sessions.kernelsessionmanager import FileKernelSessionManager
  File "/home/conda/feedstock_root/build_artifacts/jupyter_enterprise_gateway_1649803099392/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.10/site-packages/enterprise_gateway/services/sessions/kernelsessionmanager.py", line 10, in <module>
    from ipython_genutils.py3compat import (bytes_to_str, str_to_bytes)
ModuleNotFoundError: No module named 'ipython_genutils'
```

**Comment by kevin-bates** [comment]
I think the issue is more that `ipython_genutils` is not specified in the list of requirements and was essentially "resolved" via other upstream Jupyter modules.  However, those modules have probably been updated to no longer list `ipython_genutils` as a dependency - resulting in "module not found", but they had been present when EG 2.6 was built on conda-forge.  In addition, its [usage within EG has been removed](https://github.com/jupyter-server/enterprise_gateway/pull/1046) since the 2.6 release.  I think the best course of action would be to include this in the requirements file for now and we'll remove it in the next release.

**Comment by rxm7706** [comment]
@kevin-bates looks like adding ipython_genutils worked.

**Comment by kevin-bates** [comment]
Thank you for doing this @rxm7706!

**Pull request merged**
